project:
  type: website
  output-dir: docs

website:
  title: "General Conference Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Getting Started
      - href: api.qmd
        text: Documentation
      - href: technical-report.qmd
        text: Technical Report

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



